MGMT-10888: latest ui-lib image (#24)
* Renames test_and_build.yaml to on-pull-request.yaml

Workflow needs to be executed only during pull requests only

Signed-off-by: Jonathan Kilzi <jkilzi@redhat.com>

Update on-pull-request.yaml

Edit the job to run only after the following events occur:
- opened
- reopened
- synchronize
- ready_for_review
- edited

* Renames release.yaml to on-release.yaml

The job now updates openshift-assisted-ui-lib in assisted-ui by sending a PR to the repo

fix: the `uses' attribute must be a path, a Docker image, or owner/repo@ref


fix

* Renames deploy.yaml to on-push.yaml

- Add 'latest' image tag only for commits to master branch
- fix: Error: Cannot find module '.../scripts/edit-package-version.js'
- chore: updates the "get tags" step description

Updates on-push.yaml
- Uses the customDockerfile in order to speed up the image creation process

Signed-off-by: Jonathan Kilzi <jkilzi@redhat.com>

Adds scripts/edit-package-version.js

* update pkg json to use my repo

Signed-off-by: Jonathan Kilzi <jkilzi@redhat.com>

use my repo